<div class="manage-member">
	<?php $member = $this->getMember() ?>
	<div class="rsg-member-mem">Member Id : <?php echo $member->getmemberId() ?></div>
	<div class="rsg-member-nam">Name : <?php echo $member->getName() ?></div>
	<div class="rsg-member-dep">Department : <?php echo $member->getDepartment() ?></div>
	<div class="rsg-member-quo">Quotes : <?php echo $member->getQuotes() ?></div>
</div>
